server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/testDB?useSSL=false
    username: root
    password: dbadmin
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
